spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank cards related prod APIs "
  contactDetails:
    name: "Rafe Nakhuda - Developer"
    email: "nakhudarafe@gmail.com"
  onCallSupport:
    - (91) 9876543210