spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank cards related QA APIs "
  contactDetails:
    name: "Rafe Nakhuda - Developer"
    email: "nakhudarafe@gmail.com"
  onCallSupport:
    - (91) 9876543210