build:
  version: "2.0"

cards:
  message: "Welcome to Bank cards related QA APIs "
  contactDetails:
    name: "Rafe Nakhuda - Developer"
    email: "nakhudarafe@gmail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267