build:
  version: "3.0"

cards:
  message: "Welcome to Bank cards related local APIs "
  contactDetails:
    name: "Rafe Nakhuda - Developer"
    email: "nakhudarafe@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932