build:
  version: "1.0"

loans:
  message: "Welcome to Bank loans related prod APIs "
  contactDetails:
    name: "Rafe Nakhuda - Developer"
    email: "nakhudarafe@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956